version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gustav"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    ports:
      - 5432:5432

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
    - .env

    volumes:
    - .:/app/project

    depends_on:
      db:
        condition: service_healthy


  redis:
    image: redis:alpine

  celery:
    build: .
    restart: always
    volumes:
      - .:/app/project
    command: celery -A foods worker -l INFO

    depends_on:
      - redis

    depends_on:
      db:
        condition: service_healthy

    